import type { Config } from "tailwindcss";

const config: Config = {
  content: [
    "./app/**/*.{js,ts,jsx,tsx,mdx}",
    "./components/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "on-secondary": "#ffffff",
        "secondary-container": "#e2dfde",
        "on-surface-variant": "#434933",
        "primary-container": "#c7ff00",
        "surface-variant": "#e2e3e1",
        "on-primary-fixed": "#151f00",
        "surface-bright": "#f9f9f7",
        "border-light": "#E8E8E8",
        "primary-fixed-dim": "#a7d700",
        "surface-container-highest": "#e2e3e1",
        "surface": "#f9f9f7",
        "success-green": "#5FCF6A",
        "tertiary": "#556500",
        "surface-container": "#eeeeec",
        "surface-tint": "#4e6700",
        "on-primary": "#ffffff",
        "on-secondary-fixed-variant": "#474746",
        "outline-variant": "#c3caac",
        "secondary-fixed": "#e5e2e1",
        "on-tertiary": "#ffffff",
        "surface-container-lowest": "#ffffff",
        "error-container": "#ffdad6",
        "error": "#ba1a1a",
        "inverse-on-surface": "#f1f1ef",
        "on-background": "#1a1c1b",
        "text-muted": "#6F6F6F",
        "primary": "#4e6700",
        "inverse-primary": "#a7d700",
        "glow-purple": "rgba(190, 140, 255, 0.18)",
        "glow-pink": "rgba(255, 160, 210, 0.20)",
        "text-primary": "#191919",
        "inverse-surface": "#2f3130",
        "background": "#f9f9f7",
        "surface-muted": "#F1F2F0",
        "on-error-container": "#93000a",
        "primary-fixed": "#bff500",
        "warning-amber": "#F6C85F",
        "surface-dim": "#dadad8",
        "on-primary-container": "#587300",
        "on-primary-fixed-variant": "#3a4d00",
        "tertiary-container": "#e0f682",
        "tertiary-fixed": "#d7ed7a",
        "on-tertiary-fixed-variant": "#404c00",
        "surface-white": "#FFFFFF",
        "on-surface": "#1a1c1b",
        "on-error": "#ffffff",
        "secondary": "#5f5e5e",
        "secondary-fixed-dim": "#c8c6c5",
        "on-tertiary-container": "#607105",
        "danger-red": "#EF6B6B",
        "glow-blue": "rgba(125, 180, 255, 0.25)",
        "on-secondary-fixed": "#1b1c1c",
        "tertiary-fixed-dim": "#bbd061",
        "surface-container-low": "#f4f4f2",
        "outline": "#747a60",
        "surface-container-high": "#e8e8e6",
        "on-tertiary-fixed": "#181e00",
        "on-secondary-container": "#636262"
      },
      spacing: {
        "sidebar-width": "240px",
        "container-max": "1440px",
        "stack-md": "16px",
        "card-padding": "24px",
        "outer-margin": "32px",
        "gutter": "24px",
        "stack-sm": "8px",
        "stack-lg": "32px"
      },
      borderRadius: {
        "card": "24px",
      },
      fontFamily: {
        "label-button": ["Plus Jakarta Sans", "sans-serif"],
        "display-balance": ["Plus Jakarta Sans", "sans-serif"],
        "label-muted": ["Inter", "sans-serif"],
        "body-main": ["Inter", "sans-serif"],
        "title-card": ["Plus Jakarta Sans", "sans-serif"],
        "headline-hero": ["Plus Jakarta Sans", "sans-serif"],
        "headline-section": ["Plus Jakarta Sans", "sans-serif"],
        "headline-hero-mobile": ["Plus Jakarta Sans", "sans-serif"],
        "body-strong": ["Inter", "sans-serif"]
      },
      fontSize: {
        "label-button": ["13px", { lineHeight: "1.2", fontWeight: "600" }],
        "display-balance": ["42px", { lineHeight: "1.0", letterSpacing: "-0.04em", fontWeight: "800" }],
        "label-muted": ["12px", { lineHeight: "1.4", fontWeight: "400" }],
        "body-main": ["14px", { lineHeight: "1.5", fontWeight: "400" }],
        "title-card": ["15px", { lineHeight: "1.3", fontWeight: "600" }],
        "headline-hero": ["32px", { lineHeight: "1.1", letterSpacing: "-0.02em", fontWeight: "700" }],
        "headline-section": ["20px", { lineHeight: "1.25", fontWeight: "700" }],
        "headline-hero-mobile": ["26px", { lineHeight: "1.2", fontWeight: "700" }],
        "body-strong": ["14px", { lineHeight: "1.5", fontWeight: "600" }]
      },
      keyframes: {
        "pulse-glow": {
          "0%, 100%": { opacity: "1" },
          "50%": { opacity: "0.5" },
        },
      },
      animation: {
        "pulse-glow": "pulse-glow 2s cubic-bezier(0.4, 0, 0.6, 1) infinite",
      },
    },
  },
  plugins: [],
};

export default config;
